FROM osixia/openldap:1.5.0

ADD schema/java.schema /container/service/slapd/assets/config/bootstrap/schema/custom/
ADD schema/corba.schema /container/service/slapd/assets/config/bootstrap/schema/custom/