version: "3.2"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - webapp
    networks:
      - webapp
  webapp:
    image: neosmemo/memos:latest
    volumes:
      - ./memos-data/:/var/opt/memos
    restart: always
    networks:
      - webapp
networks:
  webapp:
